{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Check In",
    "description": "User check in reward system"
  },
  "host": "localhost:3000",
  "basePath": "/api/v1",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/user/login": {
      "post": {
        "description": "Login a user using card number and pin",
        "summary": "Login",
        "tags": [
          "User"
        ],
        "operationId": "UserLoginPost",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "card_number",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "pin",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/LoginResponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im16bmRha29AZ21haWwuY29tIiwiaWF0IjoxNTM3Nzc4ODQ4LCJleHAiOjE1Mzc3Nzk0NDh9.6MekqoTceLjNuw1vogoWmmlN47GV-IzHK2AvbINONEA"
              }
            }
          }
        }
      }
    },
    "/admin/check_in_location": {
      "get": {
        "description": "Create a location where users can check in",
        "summary": "Get All Check In Locations",
        "tags": [
          "Admin"
        ],
        "operationId": "AdminCheckInLocationGet",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetAllCheckInLocationsresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "data": [
                  {
                    "_id": "5ba81bb4a419742ee4af36db",
                    "name": "Muhammad Buhari International Airport",
                    "address": "Lekki, phase 1, Lagos",
                    "longitude": "7.12333",
                    "latitude": "6.422222",
                    "authorization_token": "0APANJQ5TBDOx1Qg6vc5lp5jndyyEtUjCM8pQCsO9ykYEAYaG9BJoM9wxY",
                    "__v": 0
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a location where users can check in",
        "summary": "Create Check in Location",
        "tags": [
          "Admin"
        ],
        "operationId": "AdminCheckInLocationPost",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "address",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "longitude",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "latitude",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/CreateCheckInLocationresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "data": {
                  "name": "Muhammad Buhari International Airport",
                  "token": "0APAMx7e4gdUcoZHdOupD2o9Ofa1Fdbp8jCAKj5bRg7vaPlChZP2mJFbPj"
                }
              }
            }
          }
        }
      }
    },
    "/admin/check_in_location/{location_Id}": {
      "delete": {
        "description": "Delete a check in location",
        "summary": "Delete A Check In Location",
        "tags": [
          "Admin"
        ],
        "operationId": "AdminCheckInLocationByLocationIdDelete",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "location_Id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/DeleteACheckInLocationresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "Successfully Deleted"
              }
            }
          }
        }
      }
    },
    "/admin/merchant/{merchant_Id}": {
      "delete": {
        "description": "Delete a check in location",
        "summary": "Delete A Merchant",
        "tags": [
          "Admin"
        ],
        "operationId": "AdminMerchantByMerchantIdDelete",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "merchant_Id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/DeleteAMerchantresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "Successfully Deleted"
              }
            }
          }
        }
      }
    },
    "/merchant/fetch_user": {
      "post": {
        "description": "Fetch the user account",
        "summary": "Fetch User Account",
        "tags": [
          "Merchant"
        ],
        "operationId": "MerchantFetchUserPost",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "public_key",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "card_number",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/FetchUserAccountresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "data": {
                  "_id": "5ba89f433bf9a9062466e69a",
                  "first_name": "Test",
                  "last_name": "TEST Last",
                  "card_number": "5399-2837-3626",
                  "email": "mzndako@gmail.com",
                  "account_balance": "$ 779.65"
                }
              }
            }
          }
        }
      }
    },
    "/admin/merchant": {
      "get": {
        "description": "Retreive all merchants",
        "summary": "Get All Merchants",
        "tags": [
          "Admin"
        ],
        "operationId": "AdminMerchantGet",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetAllMerchantsresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "data": [
                  {
                    "_id": "5ba81feada18895808a0fd51",
                    "company_name": "Quicktel Solution",
                    "company_address": "Abuja",
                    "email": "quicktelsolution@gmail.com",
                    "secret_key": "secret_0APARpyUL4XuieJUZwRE9QncZ76unzZYR28loV",
                    "public_key": "public_0APARpyU20EOUgjo9eu2rfLcqWPEV68cvNJv3C",
                    "__v": 0
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "description": "Create merchant",
        "summary": "Create A Merchant",
        "tags": [
          "Admin"
        ],
        "operationId": "AdminMerchantPost",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "address",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/CreateAMerchantresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "Merchant successfully created"
              }
            }
          }
        }
      }
    },
    "/user/account/change_pin": {
      "put": {
        "description": "Change the login user PIN",
        "summary": "Change PIN",
        "tags": [
          "User"
        ],
        "operationId": "UserAccountChangePinPut",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "old_pin",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "new_pin",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/ChangePinresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "Pin change successfully"
              }
            }
          }
        }
      }
    },
    "/location/check_in": {
      "post": {
        "description": "Check In user in a location",
        "summary": "Check In",
        "tags": [
          "Location"
        ],
        "operationId": "LocationCheckInPost",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "card_number",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "pin",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/CheckInresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im16bmRha29AZ21haWwuY29tIiwiaWF0IjoxNTM3Nzc4ODQ4LCJleHAiOjE1Mzc3Nzk0NDh9.6MekqoTceLjNuw1vogoWmmlN47GV-IzHK2AvbINONEA"
              }
            }
          }
        }
      }
    },
    "/admin/user/{user_Id}": {
      "delete": {
        "description": "Delete a user",
        "summary": "Delete A User",
        "tags": [
          "Admin"
        ],
        "operationId": "AdminUserByUserIdDelete",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user_Id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/DeleteAUserrequest"
            }
          },
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/DeleteAUserresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "User deleted successfully"
              }
            }
          }
        }
      }
    },
    "/admin/login": {
      "post": {
        "description": "Login into admin",
        "summary": "Login",
        "tags": [
          "Admin"
        ],
        "operationId": "AdminLoginPost",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "username",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "password",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/LoginResponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE1Mzc3NDE3NjEsImV4cCI6MTUzNzc0NTM2MX0.WRdvEm_cliCYraOKfeaexr8TivgdomKvAM-OLWgchhg"
              }
            }
          }
        }
      }
    },
    "/merchant/charge_user": {
      "post": {
        "description": "Deduct amount from the user balance",
        "summary": "Charge User",
        "tags": [
          "Merchant"
        ],
        "operationId": "MerchantChargeUserPost",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "secret_key",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "card_number",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "pin",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "amount",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/ChargeUserresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "User charged successfully"
              }
            }
          }
        }
      }
    },
    "/admin/user": {
      "get": {
        "description": "Retreive all users",
        "summary": "Get All Users",
        "tags": [
          "Admin"
        ],
        "operationId": "AdminUserGet",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetAllUsersresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "data": [
                  {
                    "home_address": {
                      "address": "Room 131, Sabo, Yaba, Lagos",
                      "longitude": 7.1222,
                      "latitude": 7.34111
                    },
                    "_id": "5ba89f433bf9a9062466e69a",
                    "email": "mzndako@gmail.com",
                    "first_name": "Muhammad",
                    "last_name": "Ndako",
                    "__v": 0,
                    "account": {
                      "total_points": 0,
                      "points": 0,
                      "_id": "5ba89f433bf9a9062466e69b",
                      "email": "mzndako@gmail.com",
                      "card_number": "5399-2837-3626",
                      "__v": 0,
                      "amount": "$ 0.00"
                    }
                  },
                  {
                    "home_address": {
                      "address": "Room 131, Sabo, Yaba, Lagos",
                      "longitude": 7,
                      "latitude": 7
                    },
                    "_id": "5ba89fb93bf9a9062466e69c",
                    "email": "test@gmail.com",
                    "first_name": "Test",
                    "last_name": "test",
                    "__v": 0,
                    "account": {
                      "total_points": 0,
                      "points": 0,
                      "_id": "5ba89fba3bf9a9062466e69d",
                      "email": "test@gmail.com",
                      "card_number": "5555-2837-3621",
                      "__v": 0,
                      "amount": "$ 0.00"
                    }
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a user",
        "summary": "Create A User",
        "tags": [
          "Admin"
        ],
        "operationId": "AdminUserPost",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CreateAUserrequest"
            }
          },
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/CreateAUserresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "Account Created Successfully"
              }
            }
          }
        }
      }
    },
    "/user/account": {
      "get": {
        "description": "Get User Account Details using the token",
        "summary": "Get Account",
        "tags": [
          "User"
        ],
        "operationId": "UserAccountGet",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetAccountresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "data": {
                  "home_address": {
                    "address": "Room 131, Sabo, Yaba, Lagos",
                    "longitude": 7.1222,
                    "latitude": 7.34111
                  },
                  "_id": "5ba89f433bf9a9062466e69a",
                  "email": "mzndako@gmail.com",
                  "first_name": "Test",
                  "last_name": "TEST Last",
                  "__v": 0,
                  "account": {
                    "total_points": 0,
                    "points": 0,
                    "_id": "5ba89f433bf9a9062466e69b",
                    "email": "mzndako@gmail.com",
                    "card_number": "5399-2837-3626",
                    "__v": 0,
                    "amount": "$ 0.00"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "description": "Update the login user account",
        "summary": "Update User Account",
        "tags": [
          "User"
        ],
        "operationId": "UserAccountPut",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "address",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "email",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateUserAccountresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "User Account updated successfully"
              }
            }
          }
        }
      }
    },
    "/user/logs": {
      "get": {
        "description": "Get user check in logs",
        "summary": "Get Logs",
        "tags": [
          "User"
        ],
        "operationId": "UserLogsGet",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetLogsresponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "data": [
                  {
                    "email": "mzndako@gmail.com",
                    "location_Id": "5ba81bb4a419742ee4af36db",
                    "address": "Lekki, phase 1, Lagos",
                    "points": 2188.58,
                    "date": "2018-09-24T09:26:27.321Z",
                    "__v": 0,
                    "amount": "$ 218.86"
                  }
                ]
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "LoginResponse": {
      "title": "LoginResponse",
      "example": {
        "status": true,
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im16bmRha29AZ21haWwuY29tIiwiaWF0IjoxNTM3Nzc4ODQ4LCJleHAiOjE1Mzc3Nzk0NDh9.6MekqoTceLjNuw1vogoWmmlN47GV-IzHK2AvbINONEA"
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "token": {
          "description": "",
          "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im16bmRha29AZ21haWwuY29tIiwiaWF0IjoxNTM3Nzc4ODQ4LCJleHAiOjE1Mzc3Nzk0NDh9.6MekqoTceLjNuw1vogoWmmlN47GV-IzHK2AvbINONEA",
          "type": "string"
        }
      },
      "required": [
        "status",
        "token"
      ]
    },
    "CreateCheckInLocationresponse": {
      "title": "Create Check in LocationResponse",
      "example": {
        "status": true,
        "data": {
          "name": "Muhammad Buhari International Airport",
          "token": "0APAMx7e4gdUcoZHdOupD2o9Ofa1Fdbp8jCAKj5bRg7vaPlChZP2mJFbPj"
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "data": {
          "$ref": "#/definitions/Data"
        }
      },
      "required": [
        "status",
        "data"
      ]
    },
    "Data": {
      "title": "Data",
      "example": {
        "name": "Muhammad Buhari International Airport",
        "token": "0APAMx7e4gdUcoZHdOupD2o9Ofa1Fdbp8jCAKj5bRg7vaPlChZP2mJFbPj"
      },
      "type": "object",
      "properties": {
        "name": {
          "description": "",
          "example": "Muhammad Buhari International Airport",
          "type": "string"
        },
        "token": {
          "description": "",
          "example": "0APAMx7e4gdUcoZHdOupD2o9Ofa1Fdbp8jCAKj5bRg7vaPlChZP2mJFbPj",
          "type": "string"
        }
      },
      "required": [
        "name",
        "token"
      ]
    },
    "DeleteACheckInLocationresponse": {
      "title": "Delete A Check In LocationResponse",
      "example": {
        "status": true,
        "message": "Successfully Deleted"
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "message": {
          "description": "",
          "example": "Successfully Deleted",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message"
      ]
    },
    "GetAllCheckInLocationsresponse": {
      "title": "Get All Check In LocationsResponse",
      "example": {
        "status": true,
        "data": [
          {
            "_id": "5ba81bb4a419742ee4af36db",
            "name": "Muhammad Buhari International Airport",
            "address": "Lekki, phase 1, Lagos",
            "longitude": "7.12333",
            "latitude": "6.422222",
            "authorization_token": "0APANJQ5TBDOx1Qg6vc5lp5jndyyEtUjCM8pQCsO9ykYEAYaG9BJoM9wxY",
            "__v": 0
          }
        ]
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "data": {
          "description": "",
          "example": [
            {
              "_id": "5ba81bb4a419742ee4af36db",
              "name": "Muhammad Buhari International Airport",
              "address": "Lekki, phase 1, Lagos",
              "longitude": "7.12333",
              "latitude": "6.422222",
              "authorization_token": "0APANJQ5TBDOx1Qg6vc5lp5jndyyEtUjCM8pQCsO9ykYEAYaG9BJoM9wxY",
              "__v": 0
            }
          ],
          "type": "array",
          "items": {
            "$ref": "#/definitions/Data5"
          }
        }
      },
      "required": [
        "status",
        "data"
      ]
    },
    "Data5": {
      "title": "Data5",
      "example": {
        "_id": "5ba81bb4a419742ee4af36db",
        "name": "Muhammad Buhari International Airport",
        "address": "Lekki, phase 1, Lagos",
        "longitude": "7.12333",
        "latitude": "6.422222",
        "authorization_token": "0APANJQ5TBDOx1Qg6vc5lp5jndyyEtUjCM8pQCsO9ykYEAYaG9BJoM9wxY",
        "__v": 0
      },
      "type": "object",
      "properties": {
        "_id": {
          "description": "",
          "example": "5ba81bb4a419742ee4af36db",
          "type": "string"
        },
        "name": {
          "description": "",
          "example": "Muhammad Buhari International Airport",
          "type": "string"
        },
        "address": {
          "description": "",
          "example": "Lekki, phase 1, Lagos",
          "type": "string"
        },
        "longitude": {
          "description": "",
          "example": "7.12333",
          "type": "string"
        },
        "latitude": {
          "description": "",
          "example": "6.422222",
          "type": "string"
        },
        "authorization_token": {
          "description": "",
          "example": "0APANJQ5TBDOx1Qg6vc5lp5jndyyEtUjCM8pQCsO9ykYEAYaG9BJoM9wxY",
          "type": "string"
        },
        "__v": {
          "description": "",
          "example": 0,
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "_id",
        "name",
        "address",
        "longitude",
        "latitude",
        "authorization_token",
        "__v"
      ]
    },
    "DeleteAMerchantresponse": {
      "title": "Delete A MerchantResponse",
      "example": {
        "status": true,
        "message": "Successfully Deleted"
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "message": {
          "description": "",
          "example": "Successfully Deleted",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message"
      ]
    },
    "FetchUserAccountresponse": {
      "title": "Fetch User AccountResponse",
      "example": {
        "status": true,
        "data": {
          "_id": "5ba89f433bf9a9062466e69a",
          "first_name": "Test",
          "last_name": "TEST Last",
          "card_number": "5399-2837-3626",
          "email": "mzndako@gmail.com",
          "account_balance": "$ 779.65"
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "data": {
          "$ref": "#/definitions/Data8"
        }
      },
      "required": [
        "status",
        "data"
      ]
    },
    "Data8": {
      "title": "Data8",
      "example": {
        "_id": "5ba89f433bf9a9062466e69a",
        "first_name": "Test",
        "last_name": "TEST Last",
        "card_number": "5399-2837-3626",
        "email": "mzndako@gmail.com",
        "account_balance": "$ 779.65"
      },
      "type": "object",
      "properties": {
        "_id": {
          "description": "",
          "example": "5ba89f433bf9a9062466e69a",
          "type": "string"
        },
        "first_name": {
          "description": "",
          "example": "Test",
          "type": "string"
        },
        "last_name": {
          "description": "",
          "example": "TEST Last",
          "type": "string"
        },
        "card_number": {
          "description": "",
          "example": "5399-2837-3626",
          "type": "string"
        },
        "email": {
          "description": "",
          "example": "mzndako@gmail.com",
          "type": "string"
        },
        "account_balance": {
          "description": "",
          "example": "$ 779.65",
          "type": "string"
        }
      },
      "required": [
        "_id",
        "first_name",
        "last_name",
        "card_number",
        "email",
        "account_balance"
      ]
    },
    "CreateAMerchantresponse": {
      "title": "Create A MerchantResponse",
      "example": {
        "status": true,
        "message": "Merchant successfully created"
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "message": {
          "description": "",
          "example": "Merchant successfully created",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message"
      ]
    },
    "ChangePinresponse": {
      "title": "Change PINResponse",
      "example": {
        "status": true,
        "message": "Pin change successfully"
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "message": {
          "description": "",
          "example": "Pin change successfully",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message"
      ]
    },
    "CheckInresponse": {
      "title": "Check InResponse",
      "example": {
        "status": true,
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im16bmRha29AZ21haWwuY29tIiwiaWF0IjoxNTM3Nzc4ODQ4LCJleHAiOjE1Mzc3Nzk0NDh9.6MekqoTceLjNuw1vogoWmmlN47GV-IzHK2AvbINONEA"
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "token": {
          "description": "",
          "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im16bmRha29AZ21haWwuY29tIiwiaWF0IjoxNTM3Nzc4ODQ4LCJleHAiOjE1Mzc3Nzk0NDh9.6MekqoTceLjNuw1vogoWmmlN47GV-IzHK2AvbINONEA",
          "type": "string"
        }
      },
      "required": [
        "status",
        "token"
      ]
    },
    "DeleteAUserrequest": {
      "title": "Delete A UserRequest",
      "example": {
        "name": "Muhammad Buhari International Airport",
        "address": "Lekki, phase 1, Lagos",
        "longitude": 7.12333,
        "latitude": 6.422222
      },
      "type": "object",
      "properties": {
        "name": {
          "description": "",
          "example": "Muhammad Buhari International Airport",
          "type": "string"
        },
        "address": {
          "description": "",
          "example": "Lekki, phase 1, Lagos",
          "type": "string"
        },
        "longitude": {
          "description": "",
          "example": 7.12333,
          "type": "number",
          "format": "double"
        },
        "latitude": {
          "description": "",
          "example": 6.422222,
          "type": "number",
          "format": "double"
        }
      },
      "required": [
        "name",
        "address",
        "longitude",
        "latitude"
      ]
    },
    "DeleteAUserresponse": {
      "title": "Delete A UserResponse",
      "example": {
        "status": true,
        "message": "User deleted successfully"
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "message": {
          "description": "",
          "example": "User deleted successfully",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message"
      ]
    },
    "ChargeUserresponse": {
      "title": "Charge UserResponse",
      "example": {
        "status": true,
        "message": "User charged successfully"
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "message": {
          "description": "",
          "example": "User charged successfully",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message"
      ]
    },
    "GetAllUsersresponse": {
      "title": "Get All UsersResponse",
      "example": {
        "status": true,
        "data": [
          {
            "home_address": {
              "address": "Room 131, Sabo, Yaba, Lagos",
              "longitude": 7.1222,
              "latitude": 7.34111
            },
            "_id": "5ba89f433bf9a9062466e69a",
            "email": "mzndako@gmail.com",
            "first_name": "Muhammad",
            "last_name": "Ndako",
            "__v": 0,
            "account": {
              "total_points": 0,
              "points": 0,
              "_id": "5ba89f433bf9a9062466e69b",
              "email": "mzndako@gmail.com",
              "card_number": "5399-2837-3626",
              "__v": 0,
              "amount": "$ 0.00"
            }
          },
          {
            "home_address": {
              "address": "Room 131, Sabo, Yaba, Lagos",
              "longitude": 7,
              "latitude": 7
            },
            "_id": "5ba89fb93bf9a9062466e69c",
            "email": "test@gmail.com",
            "first_name": "Test",
            "last_name": "test",
            "__v": 0,
            "account": {
              "total_points": 0,
              "points": 0,
              "_id": "5ba89fba3bf9a9062466e69d",
              "email": "test@gmail.com",
              "card_number": "5555-2837-3621",
              "__v": 0,
              "amount": "$ 0.00"
            }
          }
        ]
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "data": {
          "description": "",
          "example": [
            {
              "home_address": {
                "address": "Room 131, Sabo, Yaba, Lagos",
                "longitude": 7.1222,
                "latitude": 7.34111
              },
              "_id": "5ba89f433bf9a9062466e69a",
              "email": "mzndako@gmail.com",
              "first_name": "Muhammad",
              "last_name": "Ndako",
              "__v": 0,
              "account": {
                "total_points": 0,
                "points": 0,
                "_id": "5ba89f433bf9a9062466e69b",
                "email": "mzndako@gmail.com",
                "card_number": "5399-2837-3626",
                "__v": 0,
                "amount": "$ 0.00"
              }
            },
            {
              "home_address": {
                "address": "Room 131, Sabo, Yaba, Lagos",
                "longitude": 7,
                "latitude": 7
              },
              "_id": "5ba89fb93bf9a9062466e69c",
              "email": "test@gmail.com",
              "first_name": "Test",
              "last_name": "test",
              "__v": 0,
              "account": {
                "total_points": 0,
                "points": 0,
                "_id": "5ba89fba3bf9a9062466e69d",
                "email": "test@gmail.com",
                "card_number": "5555-2837-3621",
                "__v": 0,
                "amount": "$ 0.00"
              }
            }
          ],
          "type": "array",
          "items": {
            "$ref": "#/definitions/Data17"
          }
        }
      },
      "required": [
        "status",
        "data"
      ]
    },
    "Data17": {
      "title": "Data17",
      "example": {
        "home_address": {
          "address": "Room 131, Sabo, Yaba, Lagos",
          "longitude": 7.1222,
          "latitude": 7.34111
        },
        "_id": "5ba89f433bf9a9062466e69a",
        "email": "mzndako@gmail.com",
        "first_name": "Muhammad",
        "last_name": "Ndako",
        "__v": 0,
        "account": {
          "total_points": 0,
          "points": 0,
          "_id": "5ba89f433bf9a9062466e69b",
          "email": "mzndako@gmail.com",
          "card_number": "5399-2837-3626",
          "__v": 0,
          "amount": "$ 0.00"
        }
      },
      "type": "object",
      "properties": {
        "home_address": {
          "$ref": "#/definitions/HomeAddress"
        },
        "_id": {
          "description": "",
          "example": "5ba89f433bf9a9062466e69a",
          "type": "string"
        },
        "email": {
          "description": "",
          "example": "mzndako@gmail.com",
          "type": "string"
        },
        "first_name": {
          "description": "",
          "example": "Muhammad",
          "type": "string"
        },
        "last_name": {
          "description": "",
          "example": "Ndako",
          "type": "string"
        },
        "__v": {
          "description": "",
          "example": 0,
          "type": "integer",
          "format": "int32"
        },
        "account": {
          "$ref": "#/definitions/Account"
        }
      },
      "required": [
        "home_address",
        "_id",
        "email",
        "first_name",
        "last_name",
        "__v",
        "account"
      ]
    },
    "HomeAddress": {
      "title": "HomeAddress",
      "example": {
        "address": "Room 131, Sabo, Yaba, Lagos",
        "longitude": 7.1222,
        "latitude": 7.34111
      },
      "type": "object",
      "properties": {
        "address": {
          "description": "",
          "example": "Room 131, Sabo, Yaba, Lagos",
          "type": "string"
        },
        "longitude": {
          "description": "",
          "example": 7.1222,
          "type": "number",
          "format": "double"
        },
        "latitude": {
          "description": "",
          "example": 7.34111,
          "type": "number",
          "format": "double"
        }
      },
      "required": [
        "address",
        "longitude",
        "latitude"
      ]
    },
    "Account": {
      "title": "Account",
      "example": {
        "total_points": 0,
        "points": 0,
        "_id": "5ba89f433bf9a9062466e69b",
        "email": "mzndako@gmail.com",
        "card_number": "5399-2837-3626",
        "__v": 0,
        "amount": "$ 0.00"
      },
      "type": "object",
      "properties": {
        "total_points": {
          "description": "",
          "example": 0,
          "type": "integer",
          "format": "int32"
        },
        "points": {
          "description": "",
          "example": 0,
          "type": "integer",
          "format": "int32"
        },
        "_id": {
          "description": "",
          "example": "5ba89f433bf9a9062466e69b",
          "type": "string"
        },
        "email": {
          "description": "",
          "example": "mzndako@gmail.com",
          "type": "string"
        },
        "card_number": {
          "description": "",
          "example": "5399-2837-3626",
          "type": "string"
        },
        "__v": {
          "description": "",
          "example": 0,
          "type": "integer",
          "format": "int32"
        },
        "amount": {
          "description": "",
          "example": "$ 0.00",
          "type": "string"
        }
      },
      "required": [
        "total_points",
        "points",
        "_id",
        "email",
        "card_number",
        "__v",
        "amount"
      ]
    },
    "UpdateUserAccountresponse": {
      "title": "Update User AccountResponse",
      "example": {
        "status": true,
        "message": "User Account updated successfully"
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "message": {
          "description": "",
          "example": "User Account updated successfully",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message"
      ]
    },
    "GetAllMerchantsresponse": {
      "title": "Get All MerchantsResponse",
      "example": {
        "status": true,
        "data": [
          {
            "_id": "5ba81feada18895808a0fd51",
            "company_name": "Quicktel Solution",
            "company_address": "Abuja",
            "email": "quicktelsolution@gmail.com",
            "secret_key": "secret_0APARpyUL4XuieJUZwRE9QncZ76unzZYR28loV",
            "public_key": "public_0APARpyU20EOUgjo9eu2rfLcqWPEV68cvNJv3C",
            "__v": 0
          }
        ]
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "data": {
          "description": "",
          "example": [
            {
              "_id": "5ba81feada18895808a0fd51",
              "company_name": "Quicktel Solution",
              "company_address": "Abuja",
              "email": "quicktelsolution@gmail.com",
              "secret_key": "secret_0APARpyUL4XuieJUZwRE9QncZ76unzZYR28loV",
              "public_key": "public_0APARpyU20EOUgjo9eu2rfLcqWPEV68cvNJv3C",
              "__v": 0
            }
          ],
          "type": "array",
          "items": {
            "$ref": "#/definitions/Data22"
          }
        }
      },
      "required": [
        "status",
        "data"
      ]
    },
    "Data22": {
      "title": "Data22",
      "example": {
        "_id": "5ba81feada18895808a0fd51",
        "company_name": "Quicktel Solution",
        "company_address": "Abuja",
        "email": "quicktelsolution@gmail.com",
        "secret_key": "secret_0APARpyUL4XuieJUZwRE9QncZ76unzZYR28loV",
        "public_key": "public_0APARpyU20EOUgjo9eu2rfLcqWPEV68cvNJv3C",
        "__v": 0
      },
      "type": "object",
      "properties": {
        "_id": {
          "description": "",
          "example": "5ba81feada18895808a0fd51",
          "type": "string"
        },
        "company_name": {
          "description": "",
          "example": "Quicktel Solution",
          "type": "string"
        },
        "company_address": {
          "description": "",
          "example": "Abuja",
          "type": "string"
        },
        "email": {
          "description": "",
          "example": "quicktelsolution@gmail.com",
          "type": "string"
        },
        "secret_key": {
          "description": "",
          "example": "secret_0APARpyUL4XuieJUZwRE9QncZ76unzZYR28loV",
          "type": "string"
        },
        "public_key": {
          "description": "",
          "example": "public_0APARpyU20EOUgjo9eu2rfLcqWPEV68cvNJv3C",
          "type": "string"
        },
        "__v": {
          "description": "",
          "example": 0,
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "_id",
        "company_name",
        "company_address",
        "email",
        "secret_key",
        "public_key",
        "__v"
      ]
    },
    "GetLogsresponse": {
      "title": "Get LogsResponse",
      "example": {
        "status": true,
        "data": [
          {
            "email": "mzndako@gmail.com",
            "location_Id": "5ba81bb4a419742ee4af36db",
            "address": "Lekki, phase 1, Lagos",
            "points": 2188.58,
            "date": "2018-09-24T09:26:27.321Z",
            "__v": 0,
            "amount": "$ 218.86"
          }
        ]
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "data": {
          "description": "",
          "example": [
            {
              "email": "mzndako@gmail.com",
              "location_Id": "5ba81bb4a419742ee4af36db",
              "address": "Lekki, phase 1, Lagos",
              "points": 2188.58,
              "date": "2018-09-24T09:26:27.321Z",
              "__v": 0,
              "amount": "$ 218.86"
            }
          ],
          "type": "array",
          "items": {
            "$ref": "#/definitions/Data24"
          }
        }
      },
      "required": [
        "status",
        "data"
      ]
    },
    "Data24": {
      "title": "Data24",
      "example": {
        "email": "mzndako@gmail.com",
        "location_Id": "5ba81bb4a419742ee4af36db",
        "address": "Lekki, phase 1, Lagos",
        "points": 2188.58,
        "date": "2018-09-24T09:26:27.321Z",
        "__v": 0,
        "amount": "$ 218.86"
      },
      "type": "object",
      "properties": {
        "email": {
          "description": "",
          "example": "mzndako@gmail.com",
          "type": "string"
        },
        "location_Id": {
          "description": "",
          "example": "5ba81bb4a419742ee4af36db",
          "type": "string"
        },
        "address": {
          "description": "",
          "example": "Lekki, phase 1, Lagos",
          "type": "string"
        },
        "points": {
          "description": "",
          "example": 2188.58,
          "type": "number",
          "format": "double"
        },
        "date": {
          "description": "",
          "example": "9/24/2018 9:26:27 AM",
          "type": "string"
        },
        "__v": {
          "description": "",
          "example": 0,
          "type": "integer",
          "format": "int32"
        },
        "amount": {
          "description": "",
          "example": "$ 218.86",
          "type": "string"
        }
      },
      "required": [
        "email",
        "location_Id",
        "address",
        "points",
        "date",
        "__v",
        "amount"
      ]
    },
    "CreateAUserrequest": {
      "title": "Create A UserRequest",
      "example": {
        "email": "test2@gmail.com",
        "first_name": "Test",
        "last_name": "test",
        "home_address": {
          "address": "Room 131, Sabo, Yaba, Lagos",
          "longitude": 7,
          "latitude": 7
        },
        "card_number": "45555-2837-3621",
        "default_pin": "4321"
      },
      "type": "object",
      "properties": {
        "email": {
          "description": "",
          "example": "test2@gmail.com",
          "type": "string"
        },
        "first_name": {
          "description": "",
          "example": "Test",
          "type": "string"
        },
        "last_name": {
          "description": "",
          "example": "test",
          "type": "string"
        },
        "home_address": {
          "$ref": "#/definitions/HomeAddress26"
        },
        "card_number": {
          "description": "",
          "example": "45555-2837-3621",
          "type": "string"
        },
        "default_pin": {
          "description": "",
          "example": "4321",
          "type": "string"
        }
      },
      "required": [
        "email",
        "first_name",
        "last_name",
        "home_address",
        "card_number",
        "default_pin"
      ]
    },
    "HomeAddress26": {
      "title": "HomeAddress26",
      "example": {
        "address": "Room 131, Sabo, Yaba, Lagos",
        "longitude": 7,
        "latitude": 7
      },
      "type": "object",
      "properties": {
        "address": {
          "description": "",
          "example": "Room 131, Sabo, Yaba, Lagos",
          "type": "string"
        },
        "longitude": {
          "description": "",
          "example": 7,
          "type": "integer",
          "format": "int32"
        },
        "latitude": {
          "description": "",
          "example": 7,
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "address",
        "longitude",
        "latitude"
      ]
    },
    "CreateAUserresponse": {
      "title": "Create A UserResponse",
      "example": {
        "status": true,
        "message": "Account Created Successfully"
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "message": {
          "description": "",
          "example": "Account Created Successfully",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message"
      ]
    },
    "GetAccountresponse": {
      "title": "Get AccountResponse",
      "example": {
        "status": true,
        "data": {
          "home_address": {
            "address": "Room 131, Sabo, Yaba, Lagos",
            "longitude": 7.1222,
            "latitude": 7.34111
          },
          "_id": "5ba89f433bf9a9062466e69a",
          "email": "mzndako@gmail.com",
          "first_name": "Test",
          "last_name": "TEST Last",
          "__v": 0,
          "account": {
            "total_points": 0,
            "points": 0,
            "_id": "5ba89f433bf9a9062466e69b",
            "email": "mzndako@gmail.com",
            "card_number": "5399-2837-3626",
            "__v": 0,
            "amount": "$ 0.00"
          }
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "data": {
          "$ref": "#/definitions/Data17"
        }
      },
      "required": [
        "status",
        "data"
      ]
    }
  }
}